version: 2
updates:
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - dargmuesli
  assignees:
    - dargmuesli
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
