allowBuilds:
  '@dargmuesli/nuxt-vio': false
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@dargmuesli/nuxt-vio@22.0.1'
packages:
  - src
  - tests
