allowBuilds:
  '@dargmuesli/nuxt-vio': false
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@dargmuesli/nuxt-vio@22.0.2 || 23.0.0-beta.1'
  - '@dargmuesli/nuxt-vio-testing@22.0.2'
packages:
  - src
  - tests
